/**
 * Order Service
 * Leeroy Order
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.
 */
import {expect} from 'chai';
import DefaultRequests  from '../../src/api/DefaultRequests';

describe('DefaultApi', function(){
  let requests;
  beforeEach(function() {
    requests = new DefaultRequests({
        registerHandler(){
        },
        sendRequest(){
        }
    });

  });


    describe('findMenus', function() {
      it('should send request findMenus successfully', ()=> {
        //uncomment below and update the code to test findMenus
        //return requests.findMenus(storeId: number).then(response=> {
        //  if (error) throw error;
        //  expect(response).to.be();
        //});

      });
    });

});
